name: trade_alert

on:
  workflow_dispatch:

jobs:
  trade_alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update trade alert"
            git push origin trade-alert
          else
            echo "No changes to commit"
          fi

      - name: Discord 알림
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"<@${DISCORD_USER_ID}> Trade Alert 실행 완료\"}" \
               $DISCORD_WEBHOOK
